/**
 * Eviratec Entity API
 * [eviratec.com.au](https://www.eviratec.com.au) / [3xqt.co](http://www.3xqt.co)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UUserIDTypesAttributes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UUserIDTypesAttributes'));
  } else {
    // Browser globals (root is window)
    if (!root.EviratecEntityApi) {
      root.EviratecEntityApi = {};
    }
    root.EviratecEntityApi.NewEntityType = factory(root.EviratecEntityApi.ApiClient, root.EviratecEntityApi.UUserIDTypesAttributes);
  }
}(this, function(ApiClient, UUserIDTypesAttributes) {
  'use strict';




  /**
   * The NewEntityType model module.
   * @module model/NewEntityType
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>NewEntityType</code>.
   * @alias module:model/NewEntityType
   * @class
   * @param className {String} 
   * @param label {String} 
   */
  var exports = function(className, label) {
    var _this = this;


    _this['ClassName'] = className;

    _this['Label'] = label;

  };

  /**
   * Constructs a <code>NewEntityType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewEntityType} obj Optional instance to populate.
   * @return {module:model/NewEntityType} The populated <code>NewEntityType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ParentID')) {
        obj['ParentID'] = ApiClient.convertToType(data['ParentID'], 'Number');
      }
      if (data.hasOwnProperty('ClassName')) {
        obj['ClassName'] = ApiClient.convertToType(data['ClassName'], 'String');
      }
      if (data.hasOwnProperty('Slug')) {
        obj['Slug'] = ApiClient.convertToType(data['Slug'], 'String');
      }
      if (data.hasOwnProperty('Label')) {
        obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
      }
      if (data.hasOwnProperty('Attributes')) {
        obj['Attributes'] = ApiClient.convertToType(data['Attributes'], [UUserIDTypesAttributes]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} ParentID
   */
  exports.prototype['ParentID'] = undefined;
  /**
   * @member {String} ClassName
   */
  exports.prototype['ClassName'] = undefined;
  /**
   * @member {String} Slug
   */
  exports.prototype['Slug'] = undefined;
  /**
   * @member {String} Label
   */
  exports.prototype['Label'] = undefined;
  /**
   * @member {Array.<module:model/UUserIDTypesAttributes>} Attributes
   */
  exports.prototype['Attributes'] = undefined;



  return exports;
}));


