/**
 * Eviratec Entity API
 * [eviratec.com.au](https://www.eviratec.com.au) / [3xqt.co](http://www.3xqt.co)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EviratecEntity) {
      root.EviratecEntity = {};
    }
    root.EviratecEntity.TypeAttribute = factory(root.EviratecEntity.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TypeAttribute model module.
   * @module model/TypeAttribute
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TypeAttribute</code>.
   * @alias module:model/TypeAttribute
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>TypeAttribute</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TypeAttribute} obj Optional instance to populate.
   * @return {module:model/TypeAttribute} The populated <code>TypeAttribute</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TypeID')) {
        obj['TypeID'] = ApiClient.convertToType(data['TypeID'], 'Number');
      }
      if (data.hasOwnProperty('AttributeKey')) {
        obj['AttributeKey'] = ApiClient.convertToType(data['AttributeKey'], 'String');
      }
      if (data.hasOwnProperty('Label')) {
        obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
      }
      if (data.hasOwnProperty('Required')) {
        obj['Required'] = ApiClient.convertToType(data['Required'], 'Boolean');
      }
      if (data.hasOwnProperty('DefaultValue')) {
        obj['DefaultValue'] = ApiClient.convertToType(data['DefaultValue'], 'String');
      }
      if (data.hasOwnProperty('Created')) {
        obj['Created'] = ApiClient.convertToType(data['Created'], 'Date');
      }
      if (data.hasOwnProperty('Modified')) {
        obj['Modified'] = ApiClient.convertToType(data['Modified'], 'Date');
      }
      if (data.hasOwnProperty('Deleted')) {
        obj['Deleted'] = ApiClient.convertToType(data['Deleted'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Number} TypeID
   */
  exports.prototype['TypeID'] = undefined;
  /**
   * @member {String} AttributeKey
   */
  exports.prototype['AttributeKey'] = undefined;
  /**
   * @member {String} Label
   */
  exports.prototype['Label'] = undefined;
  /**
   * @member {Boolean} Required
   */
  exports.prototype['Required'] = undefined;
  /**
   * @member {String} DefaultValue
   */
  exports.prototype['DefaultValue'] = undefined;
  /**
   * @member {Date} Created
   */
  exports.prototype['Created'] = undefined;
  /**
   * @member {Date} Modified
   */
  exports.prototype['Modified'] = undefined;
  /**
   * @member {Date} Deleted
   */
  exports.prototype['Deleted'] = undefined;



  return exports;
}));


