/**
 * Eviratec Entity API
 * [eviratec.com.au](https://www.eviratec.com.au) / [3xqt.co](http://www.3xqt.co)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EviratecEntity);
  }
}(this, function(expect, EviratecEntity) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EviratecEntity.NewEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewEntity', function() {
    it('should create an instance of NewEntity', function() {
      // uncomment below and update the code to test NewEntity
      //var instane = new EviratecEntity.NewEntity();
      //expect(instance).to.be.a(EviratecEntity.NewEntity);
    });

    it('should have the property typeID (base name: "TypeID")', function() {
      // uncomment below and update the code to test the property typeID
      //var instane = new EviratecEntity.NewEntity();
      //expect(instance).to.be();
    });

    it('should have the property attributes (base name: "Attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instane = new EviratecEntity.NewEntity();
      //expect(instance).to.be();
    });

  });

}));
