/**
 * Eviratec Entity API
 * [eviratec.com.au](https://www.eviratec.com.au) / [3xqt.co](http://www.3xqt.co)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EviratecEntityApi);
  }
}(this, function(expect, EviratecEntityApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EviratecEntityApi.EntityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EntityApi', function() {
    describe('createEntity', function() {
      it('should call createEntity successfully', function(done) {
        //uncomment below and update the code to test createEntity
        //instance.createEntity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEntityByEntityID', function() {
      it('should call deleteEntityByEntityID successfully', function(done) {
        //uncomment below and update the code to test deleteEntityByEntityID
        //instance.deleteEntityByEntityID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEntityByEntityID', function() {
      it('should call getEntityByEntityID successfully', function(done) {
        //uncomment below and update the code to test getEntityByEntityID
        //instance.getEntityByEntityID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEntityList', function() {
      it('should call getEntityList successfully', function(done) {
        //uncomment below and update the code to test getEntityList
        //instance.getEntityList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
