/**
 * Eviratec Entity API
 * [eviratec.com.au](https://www.eviratec.com.au) / [3xqt.co](http://www.3xqt.co)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EviratecEntityApi);
  }
}(this, function(expect, EviratecEntityApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EviratecEntityApi.TypeAttributeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TypeAttributeApi', function() {
    describe('createTypeAttribute', function() {
      it('should call createTypeAttribute successfully', function(done) {
        //uncomment below and update the code to test createTypeAttribute
        //instance.createTypeAttribute(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTypeAttributeByAttributeKey', function() {
      it('should call getTypeAttributeByAttributeKey successfully', function(done) {
        //uncomment below and update the code to test getTypeAttributeByAttributeKey
        //instance.getTypeAttributeByAttributeKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTypeAttributeByAttributeKey', function() {
      it('should call updateTypeAttributeByAttributeKey successfully', function(done) {
        //uncomment below and update the code to test updateTypeAttributeByAttributeKey
        //instance.updateTypeAttributeByAttributeKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
